# Numpy
numeric computations

In [3]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [4]:
list1 = [1, 2, 3, 4, 5, 6]
print(list1)

[1, 2, 3, 4, 5, 6]


In [5]:
array = np.array(list1, dtype=int)
print(array)

[1 2 3 4 5 6]


In [6]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [7]:
array2 = array.reshape(3, 2)
print(array2)
print(array2.shape)

array3 = array.reshape(3, -1)
print(array3)
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
2


In [8]:
list2 = [1, 2, 3, 4, 5, 6]
list3 = [7, 8, 9, 10, 11, 12]
list4 = [13, 14, 15, 16, 17, 18]
array4 = np.array([list2, list3, list4])
print(array4)
print(array4.shape)
print(array4.reshape(-1, 3))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


## NumPy Attributes

In [22]:
a = np.array([[1, 2, 6], [3, 4, 5]])
print(a.shape)

(2, 3)


In [25]:
a.shape = (3, 2)
print(a)
b = a.reshape(3, 2)
b

[[1 2]
 [6 3]
 [4 5]]


array([[1, 2],
       [6, 3],
       [4, 5]])

In [26]:
r = range(24)
print(r)

range(0, 24)


In [35]:
c = np.arange(24) # arange is equally spaced values within a given interval
print(c)
print(c.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [36]:
d = c.reshape(6, 4, 1)
print(d)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


## Arithmetic Operations

In [9]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### np.add()
### np.subtract()
### np.multiply()
### np.divide()

In [10]:
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x.dot(y))
print(np.dot(x, y))
print(x / y)
print(np.divide(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### np.sum()

In [11]:
print(np.sum(x))
print(np.sum(y))
print(np.sum(x, axis = 0)) # sum of columns
print(np.sum(x, axis = 1)) # sum of rows
z = np.append(x, [[9, 10]], axis=0)
print(z.shape)
print(z)

10
26
[4 6]
[3 7]
(3, 2)
[[ 1  2]
 [ 3  4]
 [ 9 10]]


In [52]:
tuple1 = (1, 2, 3, 4, 5)
print(max(tuple1))
tuple1[:2]

5


(1, 2)

In [53]:
round(2.5)

2